fetch(url)
.then((res)=>res.json())
.then((data)=> console.log(data))
.catch()



const get = async () =>{
try{
const res=await fetch(url)
if(!res.ok){
const msg=`There was an error "${res.status} ${res.statusText}"`
throw new Error(msg)
}
const data = await res.json()
}catch(err){
console.log(err)
}